server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.205.197.119:3306/comp?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: xxyXXY
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true
#  security:
#    user:
#      name: user
#      password: $2a$10$6TJMaHHGVWzGVgoL8mYF1eoHDDvuX6quFwBpKm/gTiR0fEXR5j4TK
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
project:
  jwt:
    # KEY
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # Token validity period: 7 days, unit: second
    expire: 604800
    header: Authorization
file:
  doc-dir: /var/doc/